services:
  mysql:
    image: mysql:8.4
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: joqi
      MYSQL_DATABASE: joqi_mysql
      MYSQL_USER: joqi
      MYSQL_PASSWORD: joqi
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "joqi", "-pjoqi"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - joqi-drizzle-mysql:/var/lib/mysql

volumes:
  joqi-drizzle-mysql:
