services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: joqi_postgres
      POSTGRES_USER: joqi
      POSTGRES_PASSWORD: joqi
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U joqi -d joqi_postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - joqi-drizzle-postgres:/var/lib/postgresql/data

volumes:
  joqi-drizzle-postgres:
